# Generated by Django 3.0.8 on 2020-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourTGuide', '0002_donar'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=64)),
                ('distr', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=64)),
            ],
        ),
    ]
