# Generated by Django 3.0.8 on 2020-09-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YourTGuide', '0003_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requests',
            new_name='requests1',
        ),
    ]
